version: "3.2"
services:
  django:
    build: .
    container_name: 'deeptanglelabel-django'
    volumes:
        - ./db.sqlite3:/db.sqlite3
    command: ["gunicorn", "web.wsgi:application", "--workers", "5", "--bind", "0.0.0.0:8000"]
 
  nginx:
    image: nginx
    container_name: 'deeptanglelabel-nginx'
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./label/static:/static
    ports:
        - 80:80
